# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Anna Flasch BA BEd
# Description of the Site
description: Gesangspädagogin & Altistin
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Gesangsunterricht, Konzert, Hochzeit, Taufe, Beerdigung, Eventmusik, Musik, Singen, Altistin, Messe, Trauung
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: anna.flasch@gmx.at
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: anna-flasch-8b0b57206
#github_username:  thedevslot
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: annaflasch

# Name of the Author
author-name: Anna Flasch
# URL for the Image of the Author
author-image: /assets/images/profile.jpg
# 60 Words About the Author
author-about: Ich heiße Anna Flasch (geb. Spreitzgrabner) und bin leidenschaftliche Altistin und Gesangspädagogin. Seit meiner frühesten Kindheit gehört das Singen zu mir wie das Atmen. Deshalb liegt es mir besonders am Herzen sowohl als Gesangspädagogin im Bereich der Kinder-, Jugend- und Erwachsenenstimmbildung zu arbeiten aber auch als Sängerin tätig zu sein. Dabei ist die Gestaltung von (freien) Trauungen, Taufen und Beerdigungen genauso zentral wie das Wirken als Altistin im kirchenmusikalischen Bereich.
author-short: Gesangspädagogin & Altistin, 2880 Kirchberg am Wechsel, Österreich
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/anna-flasch

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
